# Generated by Django 3.0.5 on 2020-04-28 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('City', models.TextField()),
                ('Study_area', models.FileField(upload_to=None)),
                ('Added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Description', models.TextField()),
                ('Intensity', models.IntegerField()),
                ('Dispersion', models.FloatField()),
                ('Name', models.TextField()),
                ('Added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Map')),
            ],
        ),
    ]
