# Generated by Django 3.0.3 on 2020-04-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Description', models.TextField()),
                ('Intensity', models.IntegerField()),
                ('Dispersion', models.FloatField()),
                ('Name', models.TextField()),
            ],
        ),
    ]
