# Generated by Django 3.0.5 on 2020-04-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200428_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='Study_area',
        ),
    ]
