# Generated by Django 3.0.3 on 2020-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_map_study_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='Study_area',
            field=models.TextField(default=''),
        ),
    ]
