# Generated by Django 3.0.3 on 2020-07-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_map_study_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='Study_area',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='map',
            name='City',
        ),
        migrations.RemoveField(
            model_name='map',
            name='Name',
        ),
        migrations.AddField(
            model_name='map',
            name='featuresFile',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='map',
            name='featuresFileData',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='map',
            name='mapName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='map',
            name='shapeFile',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='map',
            name='shapeFileData',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='map',
            name='studyArea',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
