# Generated by Django 3.0.3 on 2020-07-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200701_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='featuresFile',
            new_name='featureFile',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='featuresFileData',
            new_name='featureFileData',
        ),
    ]
