# Generated by Django 3.0.3 on 2020-07-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20200709_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='featureFile',
            new_name='featureFilePath',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='shapeFile',
            new_name='shapeFilePath',
        ),
    ]
