# Generated by Django 3.0.3 on 2020-07-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20200709_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='Added_by',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='Dispersion',
            new_name='dispersion',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='Intensity',
            new_name='intensity',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='Map',
            new_name='map_id',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='Name',
            new_name='name',
        ),
    ]
