# Generated by Django 3.0.3 on 2020-07-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20200709_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='description',
            new_name='sourceType',
        ),
    ]
