# Generated by Django 3.0.3 on 2020-07-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20200709_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='Added_by',
            new_name='added_by',
        ),
    ]
