# Generated by Django 3.0.3 on 2020-07-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20200709_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='intensity',
            field=models.FloatField(),
        ),
    ]
